name: image_feed
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^9.2.1
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  injectable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.15.0
  freezed: ^3.2.5
  injectable_generator: ^3.0.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/mockData/